# Generated by Django 5.1.2 on 2024-10-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=15)),
                ('course_domain', models.CharField(max_length=50)),
            ],
        ),
    ]
