# Generated by Django 5.1.2 on 2024-10-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_proffesor',
            field=models.BooleanField(default=False),
        ),
    ]
