# Generated by Django 5.1.2 on 2024-10-25 16:29

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.TextField(blank=True, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
